#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#Autostart
killall bspswallow
pidof bspswallow | bspswallow &

# pgrep -x sxhkd > /devc/null || sxhkd &
wal -R &
# $HOME/.config/polybar/launch.sh & 

#Workspaces
bspc monitor -d I II III IV V VI VII 

bspc config border_width         3
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config top_padding 24
bspc config focused_border_color "#680402"


bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating sticky=on
bspc rule -a Sxiv state=floating
bspc rule -a firefox desktop='^2'
bspc rule -a Element desktop='^4'
bspc rule -a zoom state=floating
bspc rule -a discord desktop='^4'
bspc rule -a Zathura state=tiled
bspc rule -a Pamac-manager state=floating
bspc rule -a *:*:music state=floating sticky=on rectangle=900x500+900+200
bspc rule -a *:*:ranger state=floating rectangle=900x500+900+200
